---

- name: Add RabbitMQ key
  apt_key: url=https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc state=present id=6026DFCA

- name: Add Erlang repository
  apt_repository: repo='deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang' update_cache=yes

- name: Add RabbitMQ repository
  apt_repository: repo='deb https://dl.bintray.com/rabbitmq/debian bionic main' update_cache=yes

- name: Ensure RabbitMQ is installed
  apt: pkg=rabbitmq-server
