---

- import_tasks: install.deb.yml
  when: ansible_os_family == 'Debian' and not rabbitmq_docker

- import_tasks: install.yum.yml
  when: ansible_os_family == 'RedHat' and not rabbitmq_docker

- name: Ensure RabbitMQ is running
  service: name=rabbitmq-server state=started

- name: Ensure the users is removed
  become: True
  rabbitmq_user: user={{item}} state=absent
  with_items: "{{rabbitmq_users_remove}}"
  no_log: True

- name: Ensure the vhosts is present
  rabbitmq_vhost: name={{item}}
  with_items: "{{rabbitmq_vhosts}}"

- name: Ensure the users is present
  become: True
  rabbitmq_user: >
      user={{item.user}}
      password={{item.password}}
      configure_priv={{item.configure_priv|default('.*')}}
      read_priv={{item.read_priv|default('.*')}}
      write_priv={{item.write_priv|default('.*')}}
      vhost={{item.vhost|default('/')}}
      tags={{item.tags|default('')}}
  with_items: "{{rabbitmq_users}}"
  no_log: True

- name: Symlink RabbitMQ bin to sbin
  file: state=link src=/usr/lib/rabbitmq/bin dest=/usr/lib/rabbitmq/sbin

- name: Enable the plugins is installed
  become: True
  rabbitmq_plugin: names={{item}} state=enabled prefix=/usr/lib/rabbitmq
  with_items: "{{rabbitmq_plugins}}"
  notify:
    - rabbitmq restart
